#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

#####  ONLY CHANGE THIS BLOCK  ######
PROG=/opt/mosdns/mosdns # mosdns绝对路径
RES_DIR=/opt/mosdns/ # mosdns运行目录
CONF=./config.yaml   # mosdns配置文件
#####  ONLY CHANGE THIS BLOCK  ######

start_service() {
  procd_open_instance
  procd_set_param command $PROG start -d $RES_DIR -c $CONF

  procd_set_param user root
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
  procd_close_instance
  /etc/init.d/dnsmasq restart
  echo "mosdns 已启动!"
}

reload_service() {
  stop
  sleep 2s
  echo "mosdns 已启动!"
  start
}
