name: Auto Download and Split China IP List

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜 12 点执行一次 (UTC)
  push:
    branches:
      - main
    paths:
      - 'shell/.github/workflows/auto-split-ip-list.yml'  # 修改工作流时也会触发

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download China IP list
      run: |
        curl -L https://github.com/Loyalsoldier/geoip/raw/refs/heads/release/text/cn.txt -o cn.txt

    - name: Split IP List into IPv4 and IPv6
      run: |
        # 使用awk命令分割IP
        awk '{if ($1 ~ /^[0-9]+\./) print $1 > "china_ipv4.txt"; else print $1 > "china_ipv6.txt"}' cn.txt

    - name: Commit and push split files
      run: |
        git config --global user.name "nkym233"
        git config --global user.email "mail@wej.cc"
        git add china_ipv4.txt china_ipv6.txt
        git commit -m "Auto split China IP list into IPv4 and IPv6 files"
        git push origin main  # 推送更改到主分支
