name: Build Geosite

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone rules
        run: git clone https://github.com/v2fly/domain-list-community.git

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Create AI rules
        run: |
          cat <<EOF > domain-list-community/data/ai
          include:anthropic
          include:openai
          include:google-gemini
          EOF

      - name: Create custom list
        run: |
          cat <<EOF > domain-list-community/data/custom
          include:gfw
          include:ai
          include:dcard
          EOF

      - name: Build geosite.dat
        run: |
          cd domain-list-community
          go run ./ --datapath=data --outputdir=../output

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: geosite
          path: output/geosite.dat
